# -*- coding: utf-8 -*-
"""QRBT_Github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTSDm77wW_F5anKDYYvjKi8L8JkOTCJx
"""

import torch

class RolloutBuffer:
    def __init__(self):
        self.states = []
        self.actions = []
        self.log_probs = []
        self.rewards = []
        self.dones = []
        self.values = []

    def add(self, state, action, log_prob, reward, done, value):
        self.states.append(state)
        self.actions.append(action)
        self.log_probs.append(log_prob)
        self.rewards.append(reward)
        self.dones.append(done)
        self.values.append(value)

    def clear(self):
        self.__init__()

    def to_tensors(self, device):
        states = torch.stack(self.states).to(device)
        actions = torch.stack(self.actions).to(device)
        log_probs = torch.stack(self.log_probs).to(device)
        rewards = torch.tensor(self.rewards, dtype=torch.float32, device=device)
        dones = torch.tensor(self.dones, dtype=torch.float32, device=device)
        values = torch.stack(self.values).squeeze(-1).to(device)
        return states, actions, log_probs, rewards, dones, values