# -*- coding: utf-8 -*-
"""QRBT_Github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTSDm77wW_F5anKDYYvjKi8L8JkOTCJx
"""

from collections import defaultdict
import numpy as np

class ResultsAggregator:
    def __init__(self):
        self.records = defaultdict(list)

    def add_episode_info(self, workload_level: int, info: dict):
        rec = dict(info)
        rec["workload_level"] = workload_level
        self.records["episodes"].append(rec)

    def aggregate_by_level(self):
        by_level = {}
        for rec in self.records["episodes"]:
            lvl = rec["workload_level"]
            if lvl not in by_level:
                by_level[lvl] = {k: [] for k in rec.keys() if k != "workload_level"}
            for k, v in rec.items():
                if k == "workload_level":
                    continue
                by_level[lvl][k].append(v)

        summary = {}
        for lvl, metrics in by_level.items():
            summary[lvl] = {k: float(np.mean(v)) for k, v in metrics.items()}
        return summary